### ISSUE TITLE
Build failes on QNAP NAS

### ISSUE THREAD

**Issue by jschneider** [iriscouch/build-couchdb#14]
I installed the necessary stuff (at least whatever I think is necessary) using ipkg.
git clone worked.

Rake terminates very fast. Probably an error on my side. But I don't exactly understand what dependency might be missing.

```
rake --trace
(in /mnt/HDA_ROOT/tmp/build-couchdb)
rake aborted!
undefined method `[]' for nil:NilClass
/mnt/HDA_ROOT/tmp/build-couchdb/tasks/lib.rb:96:in `package_dep'
/mnt/HDA_ROOT/tmp/build-couchdb/tasks/toolchain.rake:14:in `block (2 levels) in <top (required)>'
/mnt/HDA_ROOT/tmp/build-couchdb/tasks/toolchain.rake:10:in `each'
/mnt/HDA_ROOT/tmp/build-couchdb/tasks/toolchain.rake:10:in `block in <top (required)>'
/opt/lib/ruby/1.9.1/rake.rb:1844:in `in_namespace'
/opt/lib/ruby/1.9.1/rake.rb:889:in `namespace'
/mnt/HDA_ROOT/tmp/build-couchdb/tasks/toolchain.rake:6:in `<top (required)>'
/opt/lib/ruby/1.9.1/rake.rb:1591:in `load'
/opt/lib/ruby/1.9.1/rake.rb:1591:in `load'
/opt/lib/ruby/1.9.1/rake.rb:2410:in `load_imports'
/opt/lib/ruby/1.9.1/rake.rb:2349:in `raw_load_rakefile'
/opt/lib/ruby/1.9.1/rake.rb:1978:in `block in load_rakefile'
/opt/lib/ruby/1.9.1/rake.rb:2029:in `standard_exception_handling'
/opt/lib/ruby/1.9.1/rake.rb:1977:in `load_rakefile'
/opt/lib/ruby/1.9.1/rake.rb:1962:in `block in run'
/opt/lib/ruby/1.9.1/rake.rb:2029:in `standard_exception_handling'
/opt/lib/ruby/1.9.1/rake.rb:1960:in `run'
/opt/bin/rake:31:in `<main>'
```

**Comment by jhs** [comment]
Thanks for the feedback! I hadn't heard of the QNAP NAS but it looks cool. What Linux distribution is it most similar to?

I am excited to add support to this device, but we might have to be patient, with a bit of back and forth.

To start out, I believe there are two bugs:
1. The script is not correctly detecting your operating system / distribution
2. It is proceeding despite that problem and crashing later in the code path

What might also be helpful is to look at the distribution detection software and see if you can translate some of that in your SSH prompt and determine whether similar functionality can identify this NAS. (For example, instead of `/etc/debian_version`, maybe there is `/opt/etc/debian_version`).
