### ISSUE TITLE
Rake fails with undefined method '[]' for nil:NilClass

### ISSUE THREAD

**Issue by wulftone** [iriscouch/build-couchdb#30]
I tried running through the README.md and got stalled at "Just run rake": `rake`

```
~/build-couchdb $ rake --trace
rake aborted!
undefined method `[]' for nil:NilClass
/home/trevor/build-couchdb/tasks/lib/package_dep.rb:23:in `package_dep'
/home/trevor/build-couchdb/tasks/toolchain.rake:13:in `block (2 levels) in <top (required)>'
/home/trevor/build-couchdb/tasks/toolchain.rake:9:in `each'
/home/trevor/build-couchdb/tasks/toolchain.rake:9:in `block in <top (required)>'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task_manager.rb:207:in `in_namespace'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/dsl_definition.rb:102:in `namespace'
/home/trevor/build-couchdb/tasks/toolchain.rake:6:in `<top (required)>'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/default_loader.rb:6:in `load'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:569:in `load_imports'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:508:in `raw_load_rakefile'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `load'
/home/trevor/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `<main>'
```

It appears to be unable to detect my distro (LinuxMint 11).  The `detect_distro()` function might be better served raising an error if it can't detect a distro...?

I do have the lsb-release file:

```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=11
DISTRIB_CODENAME=katya
DISTRIB_DESCRIPTION="Linux Mint 11 Katya"
```

Updating distros.rb now.... will report back with a pull if it works

**Comment by wulftone** [comment]
fixed with: https://github.com/iriscouch/build-couchdb/pull/31
