### ISSUE TITLE
rake aborted with config.log: No such file or directory on Ubuntu 11.10

### ISSUE THREAD

**Issue by glorylo** [iriscouch/build-couchdb#38]
Hi there,

I am new to couchdb and wanted to build from source.  I tried running the rake command but it aborts w/ config.log: no such file or directory.  any clue as to what is happening?  (I ran the dependency installs and simply followed the instructions).

My trace:

~/build-couchdb$ rake --trace
*\* Invoke default (first_time)
*\* Invoke couchdb:build (first_time)
*\* Invoke couchdb:couchdb (first_time)
*\* Invoke erlang:build (first_time)
*\* Invoke known_distro (first_time)
*\* Invoke known_checkout (first_time)
*\* Execute known_checkout
*\* Execute known_distro
*\* Invoke build:otp_git_submodules (first_time)
Build CouchDB commit: 14effdd48c87443f06a84d6873dc029109ca48fc
*\* Invoke /home/glory/build-couchdb/dependencies/otp/otp_build (first_time, not_needed)
*\* Execute build:otp_git_submodules
*\* Invoke build:os_dependencies (first_time)
*\* Invoke build:mac_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:mac_dependencies
*\* Invoke build:ubuntu_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:ubuntu_dependencies
*\* Invoke build:debian_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:debian_dependencies
*\* Invoke build:opensuse_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:opensuse_dependencies
*\* Invoke build:solaris_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:solaris_dependencies
*\* Execute build:os_dependencies
*\* Invoke environment:path (first_time)
*\* Invoke /home/glory/build-couchdb/build/bin (first_time, not_needed)
*\* Invoke known_distro 
*\* Execute environment:path
*\* Invoke /home/glory/build-couchdb/build/bin/erl (first_time)
*\* Invoke /home/glory/build-couchdb/build/bin/autoconf2.59 (first_time)
*\* Invoke / (first_time, not_needed)
*\* Execute /home/glory/build-couchdb/build/bin/autoconf2.59
*\* Invoke environment:path 
/home/glory/build-couchdb/dependencies/autoconf-2.59/configure --prefix=/home/glory/build-couchdb/build --program-suffix=2.59
== Output of config.log ==
cat config.log
cat: config.log: No such file or directory
rake aborted!
Command failed with status (1): [cat config.log...]
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in`call'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `sh'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in`sh'
/home/glory/build-couchdb/tasks/lib.rb:188:in `ensure in show_file'
/home/glory/build-couchdb/tasks/lib.rb:189:in`show_file'
/home/glory/build-couchdb/tasks/toolchain.rake:29:in `block (5 levels) in <top (required)>'
/home/glory/build-couchdb/tasks/toolchain.rake:18:in`chdir'
/home/glory/build-couchdb/tasks/toolchain.rake:18:in `block (4 levels) in <top (required)>'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/tmpdir.rb:83:in`mktmpdir'
/home/glory/build-couchdb/tasks/toolchain.rake:17:in `block (3 levels) in <top (required)>'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:203:in`call'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:203:in `block in execute'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:200:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/home/glory/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:112:in`invoke_task'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in`each'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:62:in`block in run'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'
/home/glory/.rvm/gems/ruby-1.9.2-head/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/glory/.rvm/gems/ruby-1.9.2-head/bin/rake:19:in`load'
/home/glory/.rvm/gems/ruby-1.9.2-head/bin/rake:19:in `<main>'
Tasks: TOP => default => couchdb:build => couchdb:couchdb => erlang:build => /home/glory/build-couchdb/build/bin/erl => /home/glory/build-couchdb/build/bin/autoconf2.59

**Comment by jhs** [comment]
Interesting. Did you run `git submodule init && git submodule update` before running rake? Thanks.

**Comment by glorylo** [comment]
I can't remember if I forgot that step.  I will try it again tonight.   I
will let you know.

Glory

On Fri, Mar 9, 2012 at 8:26 AM, Jason Smith <
reply@reply.github.com

**Comment by akaspin** [comment]
Same error. Same messages. I run `git submodule init && git submodule update` before running rake.

UPD: It seems that I forget to turn off `autocrlf` in Git. After I set it to `false` all builds fine. I think that it should be mentioned in README.

**Comment by iddo** [comment]
I had the same issue, it would be nice if this was documented

**Comment by glorylo** [comment]
Sorry to hear.  I had to clean my machine and have not reinstalled it.

I did install it building from source.
On Jun 9, 2012 12:38 AM, "iddo" <
reply@reply.github.com>
wrote:
