### ISSUE TITLE
rake failing with status (2): [make ...] on or around couchdb.rake:79 on MacOS X 10.7.3

### ISSUE THREAD

**Issue by nbartlow** [iriscouch/build-couchdb#48]
OS: Mac OS X - 10.7.3

rake failing with status (2): [make ...] on or around couchdb.rake:79

user@machine:~/build-couchdb 17:17:56 $ rake install=~/build-couchdb/ --trace
...
Making all in src
Making all in couchdb
Making all in priv
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy   -I$INSTALL_DIR//lib/erlang/usr/include -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include   -O2 -g -O2 -MT couch_icu_driver_la-couch_icu_driver.lo -MD -MP -MF .deps/couch_icu_driver_la-couch_icu_driver.Tpo -c -o couch_icu_driver_la-couch_icu_driver.lo `test -f 'icu_driver/couch_icu_driver.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`icu_driver/couch_icu_driver.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy -I$INSTALL_DIR//lib/erlang/usr/include -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include -O2 -g -O2 -MT couch_icu_driver_la-couch_icu_driver.lo -MD -MP -MF .deps/couch_icu_driver_la-couch_icu_driver.Tpo -c $INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/icu_driver/couch_icu_driver.c  -fno-common -DPIC -o .libs/couch_icu_driver_la-couch_icu_driver.o
$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/icu_driver/couch_icu_driver.c:171: warning: initialization from incompatible pointer type
mv -f .deps/couch_icu_driver_la-couch_icu_driver.Tpo .deps/couch_icu_driver_la-couch_icu_driver.Plo
/bin/sh ../../../libtool --tag=CC   --mode=link gcc  -O2 -g -O2 -module -avoid-version  -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib  -o couch_icu_driver.la -rpath $INSTALL_DIR/lib/couchdb/erlang/lib/couch-1.2.0/priv/lib couch_icu_driver_la-couch_icu_driver.lo -lpthread -lm   -L$INSTALL_DIR/lib -licui18n -licuuc -licudata  -lpthread -lm    -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib 
libtool: link: gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/couch_icu_driver.so -bundle  .libs/couch_icu_driver_la-couch_icu_driver.o   -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib -L$INSTALL_DIR/lib -licui18n -licuuc -licudata -lpthread -lm  -O2 -O2  
libtool: link: ( cd ".libs" && rm -f "couch_icu_driver.la" && ln -s "../couch_icu_driver.la" "couch_icu_driver.la" )
/bin/sh ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy  -D_BSD_SOURCE  -I$INSTALL_DIR//lib/erlang/usr/include -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include   -O2 -g -O2 -MT couch_ejson_compare_la-couch_ejson_compare.lo -MD -MP -MF .deps/couch_ejson_compare_la-couch_ejson_compare.Tpo -c -o couch_ejson_compare_la-couch_ejson_compare.lo `test -f 'couch_ejson_compare/couch_ejson_compare.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`couch_ejson_compare/couch_ejson_compare.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy -D_BSD_SOURCE -I$INSTALL_DIR//lib/erlang/usr/include -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include -O2 -g -O2 -MT couch_ejson_compare_la-couch_ejson_compare.lo -MD -MP -MF .deps/couch_ejson_compare_la-couch_ejson_compare.Tpo -c $INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/couch_ejson_compare/couch_ejson_compare.c  -fno-common -DPIC -o .libs/couch_ejson_compare_la-couch_ejson_compare.o
mv -f .deps/couch_ejson_compare_la-couch_ejson_compare.Tpo .deps/couch_ejson_compare_la-couch_ejson_compare.Plo
/bin/sh ../../../libtool --tag=CC   --mode=link gcc  -O2 -g -O2 -module -avoid-version  -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib  -o couch_ejson_compare.la -rpath $INSTALL_DIR/lib/couchdb/erlang/lib/couch-1.2.0/priv/lib couch_ejson_compare_la-couch_ejson_compare.lo -lpthread -lm   -L$INSTALL_DIR/lib -licui18n -licuuc -licudata  -lpthread -lm    -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib 
libtool: link: gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/couch_ejson_compare.so -bundle  .libs/couch_ejson_compare_la-couch_ejson_compare.o   -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib -L$INSTALL_DIR/lib -licui18n -licuuc -licudata -lpthread -lm  -O2 -O2  
libtool: link: ( cd ".libs" && rm -f "couch_ejson_compare.la" && ln -s "../couch_ejson_compare.la" "couch_ejson_compare.la" )
cp $INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/spawnkillable/couchspawnkillable.sh couchspawnkillable
chmod +x couchspawnkillable
gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy   -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -O2 -g -O2 -MT couchjs-http.o -MD -MP -MF .deps/couchjs-http.Tpo -c -o couchjs-http.o `test -f 'couch_js/http.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`couch_js/http.c
mv -f .deps/couchjs-http.Tpo .deps/couchjs-http.Po
gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy   -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -O2 -g -O2 -MT couchjs-main.o -MD -MP -MF .deps/couchjs-main.Tpo -c -o couchjs-main.o `test -f 'couch_js/main.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`couch_js/main.c
mv -f .deps/couchjs-main.Tpo .deps/couchjs-main.Po
gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy   -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -O2 -g -O2 -MT couchjs-utf8.o -MD -MP -MF .deps/couchjs-utf8.Tpo -c -o couchjs-utf8.o `test -f 'couch_js/utf8.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`couch_js/utf8.c
mv -f .deps/couchjs-utf8.Tpo .deps/couchjs-utf8.Po
gcc -DHAVE_CONFIG_H -I. -I$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv -I../../.. -I../../../src/snappy/google-snappy   -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -O2 -g -O2 -MT couchjs-util.o -MD -MP -MF .deps/couchjs-util.Tpo -c -o couchjs-util.o `test -f 'couch_js/util.c' || echo '$INSTALL_DIR/dependencies/couchdb/src/couchdb/priv/'`couch_js/util.c
mv -f .deps/couchjs-util.Tpo .deps/couchjs-util.Po
/bin/sh ../../../libtool --tag=CC   --mode=link gcc -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include  -O2 -g -O2 -L$INSTALL_DIR//lib -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib  -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib  -o couchjs couchjs-http.o couchjs-main.o couchjs-utf8.o couchjs-util.o -L$INSTALL_DIR/lib -lcurl -L$INSTALL_DIR//lib -L/opt/local/lib -lidn -lssl -lcrypto -lldap -lssl -lcrypto -lz -lz -lmozjs -lm   -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib  -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib 
libtool: link: gcc -g -Wall -Werror -D_BSD_SOURCE -I$INSTALL_DIR/include -DXP_UNIX -I$INSTALL_DIR//include/js -I$INSTALL_DIR//include/js/js -I$INSTALL_DIR//include/js/mozjs -I$INSTALL_DIR//include -I$INSTALL_DIR//include/js -I/opt/local/include -I/usr/local/include -I/usr/include -O2 -g -O2 -o couchjs couchjs-http.o couchjs-main.o couchjs-utf8.o couchjs-util.o  -L$INSTALL_DIR//lib -L/opt/local/lib -L/usr/local/lib -L$INSTALL_DIR/lib $INSTALL_DIR/lib/libcurl.dylib /opt/local/lib/libidn.dylib /opt/local/lib/libintl.dylib -lc /opt/local/lib/libiconv.dylib -lldap -lssl -lcrypto -lz -lmozjs -lm
touch couchjs.1
if test -x "/opt/local/bin/help2man"; then \
        /opt/local/bin/help2man --no-info --help-option="-h" --version-option="-V" \
            --name="Apache CouchDB JavaScript interpreter" ./couchjs --output couchjs.1; \
    fi
sh: line 1: 43793 Trace/BPT trap: 5       ./couchjs -h 2> /dev/null
help2man: can't get `-h' info from ./couchjs
Try`--no-discard-stderr' if option outputs to stderr
make[4]: **\* [couchjs.1] Error 133
make[3]: **\* [all-recursive] Error 1
make[2]: **\* [all-recursive] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2
git checkout HEAD src/couchdb/priv/couch_js/utf8.h
git ls-files --others --ignored --exclude-standard | xargs rm -vf
INSTALL
Makefile.in
acinclude.m4
aclocal.m4
bin/Makefile.in
config.h.in
configure
etc/Makefile.in
etc/couchdb/Makefile.in
etc/default/Makefile.in
etc/init/Makefile.in
etc/launchd/Makefile.in
etc/logrotate.d/Makefile.in
etc/windows/Makefile.in
m4/ac_check_curl.m4
m4/ac_check_icu.m4
m4/libtool.m4
m4/ltoptions.m4
m4/ltsugar.m4
m4/ltversion.m4
m4/lt~obsolete.m4
m4/pkg.m4
share/Makefile.in
src/Makefile.in
src/couchdb/Makefile.in
src/couchdb/priv/Makefile.in
src/ejson/Makefile.in
src/erlang-oauth/Makefile.in
src/etap/Makefile.in
src/ibrowse/Makefile.in
src/mochiweb/Makefile.in
src/snappy/Makefile.in
test/Makefile.in
test/bench/Makefile.in
test/etap/Makefile.in
test/javascript/Makefile.in
test/view_server/Makefile.in
utils/Makefile.in
var/Makefile.in
rake aborted!
Command failed with status (2): [make ...]
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:995:in `sh'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1010:in`call'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1010:in `sh'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1094:in`sh'
$INSTALL_DIR/tasks/lib.rb:142:in `gmake'
$INSTALL_DIR/tasks/couchdb.rake:79
$INSTALL_DIR/tasks/couchdb.rake:74:in`chdir'
$INSTALL_DIR/tasks/couchdb.rake:74
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tmpdir.rb:129:in `mktmpdir'
$INSTALL_DIR/tasks/couchdb.rake:73
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:636:in`call'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:631:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:597:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:596:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2051:in`invoke_task'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2029:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2001:in`run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1998:in`run'
/usr/bin/rake:31

**Comment by nbartlow** [comment]
A colleague of mine identified the following workaround:

changing line 70 of ../dependencies/couchdb/src/couchdb/priv/Makefile.am from: 

HELP2MAN_OPTION=--no-info --help-option="-h" --version-option="-V"

to:

HELP2MAN_OPTION=--no-info --help-option="-h" --version-option="-V" --no-discard-stderr

seems to allow the build to succeed and couch to start.

**Comment by danfairs** [comment]
I can confirm the issue is present as of 0e22abd94d08a22d483f38448b94d19f0132ae65 and that the workaround above worked for me. Same OS version.
