### ISSUE TITLE
rake build fails with undefined method `[]' for nil:NilClass on Linux Mint (Ubuntu)

### ISSUE THREAD

**Issue by ghachey** [iriscouch/build-couchdb#50]
OS - Mint Lisa
ruby - 1.8-full installed
Erlang - 1:14.b.2 installed

Followed steps and it all worked out successfully until the rake build.

Full trace:

```
$ rake --trace
(in /home/ghachey/Documents/Development/Git/build-couchdb)
rake aborted!
undefined method `[]' for nil:NilClass
/home/ghachey/Documents/Development/Git/build-couchdb/tasks/lib/package_dep.rb:23:in `package_dep'
/home/ghachey/Documents/Development/Git/build-couchdb/tasks/toolchain.rake:13
/home/ghachey/Documents/Development/Git/build-couchdb/tasks/toolchain.rake:9:in `each'
/home/ghachey/Documents/Development/Git/build-couchdb/tasks/toolchain.rake:9
/usr/lib/ruby/1.8/rake.rb:1882:in `in_namespace'
/usr/lib/ruby/1.8/rake.rb:910:in `namespace'
/home/ghachey/Documents/Development/Git/build-couchdb/tasks/toolchain.rake:6
/usr/lib/ruby/1.8/rake.rb:1620:in `load'
/usr/lib/ruby/1.8/rake.rb:1620:in `load'
/usr/lib/ruby/1.8/rake.rb:2451:in `load_imports'
/usr/lib/ruby/1.8/rake.rb:2390:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
```
## 

GH

**Comment by ghachey** [comment]
This is the same problem as in #31 (sorry, it slipped by eyes). The provided patch in #31 is a workaround that problem.

## 

GH
