### ISSUE TITLE
Missing config.log

### ISSUE THREAD

**Issue by ghost** [iriscouch/build-couchdb#74]
The current build fails (OSX 10.8.2, git 1.8.1.5, gcc 4.2.1, and ruby 2.0.0p0) with the error that config.log is missing.

*\* Invoke /Users/amckean/Desktop/build-couchdb/build/bin/autoconf2.62 (first_time, not_needed)
*\* Invoke / (not_needed)
*\* Execute /Users/amckean/Desktop/build-couchdb/build/bin/libtool
*\* Invoke environment:path 
/Users/amckean/Desktop/build-couchdb/build/bin/autoconf2.62 => /Users/amckean/Desktop/build-couchdb/build/bin/autoconf
/Users/amckean/Desktop/build-couchdb/build/bin/autoreconf2.62 => /Users/amckean/Desktop/build-couchdb/build/bin/autoreconf
/Users/amckean/Desktop/build-couchdb/build/bin/autoheader2.62 => /Users/amckean/Desktop/build-couchdb/build/bin/autoheader
/Users/amckean/Desktop/build-couchdb/build/bin/autom4te2.62 => /Users/amckean/Desktop/build-couchdb/build/bin/autom4te
/Users/amckean/Desktop/build-couchdb/dependencies/libtool/configure --prefix=/Users/amckean/Desktop/build-couchdb/build
== Output of config.log ==
cat config.log
cat: config.log: No such file or directory
git reset --hard
HEAD is now at fdb4c54 Release 2.4.2.
git clean -f -d
git ls-files --others -i --exclude-standard | xargs rm -f || true
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoconf
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoreconf
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoheader
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autom4te
rake aborted!
Command failed with status (1): [cat config.log...]
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/file_utils.rb:53:in `block in create_shell_runner'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/file_utils.rb:45:in`call'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/file_utils.rb:45:in `sh'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/file_utils_ext.rb:40:in`sh'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:197:in `ensure in show_file'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:198:in`show_file'
/Users/amckean/Desktop/build-couchdb/tasks/toolchain.rake:65:in `block (4 levels) in <top (required)>'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:217:in`block in git_work'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:215:in `chdir'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:215:in`git_work'
/Users/amckean/Desktop/build-couchdb/tasks/toolchain.rake:64:in `block (3 levels) in <top (required)>'
/Users/amckean/Desktop/build-couchdb/tasks/lib.rb:235:in`with_autoconf'
/Users/amckean/Desktop/build-couchdb/tasks/toolchain.rake:63:in `block (2 levels) in <top (required)>'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:226:in`call'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:226:in `block in execute'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:223:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:166:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:187:in `block in invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:185:in `invoke_prerequisites'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:165:in`block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:143:in`invoke_task'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:101:in`each'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:110:in`run_with_threads'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:73:in`block in run'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rake/application.rb:70:in`run'
/usr/local/bin/rake:37:in `<main>'
Tasks: TOP => default => couchdb:build => couchdb:couchdb => curl:build => /Users/amckean/Desktop/build-couchdb/build/bin/curl => /Users/amckean/Desktop/build-couchdb/build/bin/automake => /Users/amckean/Desktop/build-couchdb/build/bin/libtool

**Comment by janl** [comment]
ruby 2.0 is likely an issue here. can you try 1.8 or 1.9?

**Comment by janl** [comment]
ruby 2.0 is likely an issue here. can you try 1.8 or 1.9?

**Comment by ghost** [comment]
I'll give it a try.

Thanks

**Comment by ghost** [comment]
Still fails with Ruby 1.8.7. 

ers/amckean/Desktop/build-couchdb/build
== Output of config.log ==
cat config.log
cat: config.log: No such file or directory
git reset --hard
HEAD is now at fdb4c54 Release 2.4.2.
git clean -f -d
git ls-files --others -i --exclude-standard | xargs rm -f || true
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoconf
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoreconf
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autoheader
rm_f /Users/amckean/Desktop/build-couchdb/build/bin/autom4te
rake aborted!
Command failed with status (1): [cat config.log...]

**Comment by ghost** [comment]
I'm going to try it on Lion.

**Comment by ghost** [comment]
Tried on Lion. My machine did not have aclocal, so I installed autoconf, automaker, and lib tool (just to be sure. Now I get the error:

Making all in doc
Updating /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/version.texi
restore=: && backupdir=".am$$" && \
    am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc && \
    rm -rf $backupdir && mkdir $backupdir && \
    if (/bin/sh /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/build-aux/missing --run makeinfo --version) >/dev/null 2>&1; then \
      for f in /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.info /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.info-[0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.info-[0-9][0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.i[0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.i[0-9][0-9]; do \
        if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
      done; \
    else :; fi && \
    cd "$am__cwd"; \
    if /bin/sh /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/build-aux/missing --run makeinfo --no-split  -I /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc \
     -o /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.info /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.texi; \
    then \
      rc=0; \
      CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc; \
    else \
      rc=$?; \
      CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc && \
      $restore $backupdir/\* `echo ".//Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.info" | sed 's|[^/]*$||'`; \
    fi; \
    rm -rf $backupdir; exit $rc
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/autoconf.texi:17877: warning: `.' or`,' must follow @xref, not `f'.
restore=: && backupdir=".am$$" && \
    am__cwd=`pwd`&& CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc && \
    rm -rf $backupdir && mkdir $backupdir && \
    if (/bin/sh /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/build-aux/missing --run makeinfo --version) >/dev/null 2>&1; then \
      for f in /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info-[0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info-[0-9][0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.i[0-9] /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.i[0-9][0-9]; do \
        if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
      done; \
    else :; fi && \
    cd "$am__cwd"; \
    if /bin/sh /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/build-aux/missing --run makeinfo --no-split  -I /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc \
     -o /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi; \
    then \
      rc=0; \
      CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc; \
    else \
      rc=$?; \
      CDPATH="${ZSH_VERSION+.}:" && cd /Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc && \
      $restore $backupdir/*`echo ".//Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info" | sed 's|[^/]_$||'`; \
    fi; \
    rm -rf $backupdir; exit $rc
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Unknown command`guilsinglleft'.
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Misplaced {.
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Misplaced }.
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Unknown command `guilsinglright'.
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Misplaced {.
/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.texi:3229: Misplaced }.
makeinfo: Removing output file`/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info' due to errors; use --force to preserve.
make[2]: *_\* [/Users/amckean/Desktop/build-couchdb/dependencies/autoconf-2.69/doc/standards.info] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2
git checkout HEAD .
rm -rf autom4te.cache
rake aborted!
Command failed with status (2): [make ...]

Tasks: TOP => default => couchdb:build => couchdb:couchdb => /Users/amckean/Desktop/build-couchdb/build/bin/couchdb => /Users/amckean/Desktop/build-couchdb/build/bin/autoconf2.69
(See full trace by running task with --trace)
