### ISSUE TITLE
Missing package: libxslt1-dev (i have it)

### ISSUE THREAD

**Issue by LeHibou** [iriscouch/build-couchdb#93]
Hello,

rake tell me that i am missing a library that i have installed.

Here is the trace :

---

*\* Invoke default (first_time)
*\* Invoke couchdb:build (first_time)
*\* Invoke couchdb:couchdb (first_time)
*\* Invoke erlang:build (first_time)
*\* Invoke known_distro (first_time)
*\* Invoke known_checkout (first_time)
*\* Execute known_checkout
*\* Execute known_distro
*\* Invoke build:otp_git_submodules (first_time)
*\* Invoke /path/to/executable/build-couchdb/dependencies/otp/otp_build (first_time, not_needed)
*\* Execute build:otp_git_submodules
*\* Invoke build:os_dependencies (first_time)
*\* Invoke build:mac_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:mac_dependencies
*\* Invoke build:ubuntu_dependencies (first_time)
*\* Invoke known_distro 
*\* Execute build:ubuntu_dependencies
rake aborted!
Missing package: libxslt1-dev
/path/to/executable/build-couchdb/tasks/lib.rb:160:in `block in install_packages'
/path/to/executable/build-couchdb/tasks/lib.rb:177:in`call'
/path/to/executable/build-couchdb/tasks/lib.rb:177:in `block in install_packages'
/path/to/executable/build-couchdb/tasks/lib.rb:176:in`each'
/path/to/executable/build-couchdb/tasks/lib.rb:176:in `install_packages'
/path/to/executable/build-couchdb/tasks/all.rake:61:in`block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in`block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in`execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in`block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in`invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in`block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in`invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in`block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in`invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in`block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in`invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in`block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in`invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:170:in`invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:143:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in`block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in`block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:95:in`top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:73:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in`standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in`<main>'
Tasks: TOP => default => couchdb:build => couchdb:couchdb => erlang:build => build:os_dependencies => build:ubuntu_dependencies

---

Any hints ?

Thanks !

**Comment by mobiniustechnologies** [comment]
@LeHibou : are you running Ubuntu 14.04 LTS ?
