### ISSUE TITLE
rake fails on openSUSE 12.3

### ISSUE THREAD

**Issue by csbrandt** [iriscouch/build-couchdb#97]
~/build-couchdb> rake
Build CouchDB commit: 386709164263df752caabbad15c136dd908ce323
Missing package: rubygem-rake
Try: sudo zypper install rubygem-rake
## 

rake aborted!
Missing package: rubygem-rake
build-couchdb/tasks/lib.rb:160:in `block in install_packages'
build-couchdb/tasks/lib.rb:167:in`call'
build-couchdb/tasks/lib.rb:167:in `block in install_packages'
build-couchdb/tasks/lib.rb:166:in`each'
build-couchdb/tasks/lib.rb:166:in `install_packages'
build-couchdb/tasks/all.rake:69:in`block (2 levels) in <top (required)>'
Tasks: TOP => default => couchdb:build => couchdb:couchdb => erlang:build => build:os_dependencies => build:opensuse_dependencies
(See full trace by running task with --trace)

~/build-couchdb> sudo zypper install rubygem-rake
Loading repository data...
Reading installed packages...
'rubygem-rake' not found in package names. Trying capabilities.
'ruby' providing 'rubygem-rake' is already installed.
Resolving package dependencies...

Nothing to do.

~/build-couchdb> cat /etc/SuSE-release
openSUSE 12.3 (x86_64)
VERSION = 12.3
CODENAME = Dartmouth

**Comment by csbrandt** [comment]
For openSUSE 12.3 run the following as root:

zypper addrepo http://download.opensuse.org/repositories/devel:languages:ruby:extensions/openSUSE_12.3/devel:languages:ruby:extensions.repo
zypper refresh
zypper install rubygem-rake
